// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOX4l11nBJYeryvQsI66l0kLPk-rCgFr8',
    appId: '1:933833543524:web:3a5c5a838225cff92a3471',
    messagingSenderId: '933833543524',
    projectId: 'fb-final-project-8bcfe',
    authDomain: 'fb-final-project-8bcfe.firebaseapp.com',
    storageBucket: 'fb-final-project-8bcfe.firebasestorage.app',
    measurementId: 'G-H6X07HKEWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9zZJlZnd6CEknEo0jaalaRrK34qtfZb4',
    appId: '1:933833543524:android:f7a56defee2ca8452a3471',
    messagingSenderId: '933833543524',
    projectId: 'fb-final-project-8bcfe',
    storageBucket: 'fb-final-project-8bcfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjXiZCwO53bHEq6yGQkvQno6Nt4nUrPs',
    appId: '1:933833543524:ios:794590dfb43319d52a3471',
    messagingSenderId: '933833543524',
    projectId: 'fb-final-project-8bcfe',
    storageBucket: 'fb-final-project-8bcfe.firebasestorage.app',
    iosBundleId: 'com.example.socialanxiProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjXiZCwO53bHEq6yGQkvQno6Nt4nUrPs',
    appId: '1:933833543524:ios:794590dfb43319d52a3471',
    messagingSenderId: '933833543524',
    projectId: 'fb-final-project-8bcfe',
    storageBucket: 'fb-final-project-8bcfe.firebasestorage.app',
    iosBundleId: 'com.example.socialanxiProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOX4l11nBJYeryvQsI66l0kLPk-rCgFr8',
    appId: '1:933833543524:web:d0d56389d24cd3a92a3471',
    messagingSenderId: '933833543524',
    projectId: 'fb-final-project-8bcfe',
    authDomain: 'fb-final-project-8bcfe.firebaseapp.com',
    storageBucket: 'fb-final-project-8bcfe.firebasestorage.app',
    measurementId: 'G-WECPE7QYBZ',
  );
}
